### ISSUE TITLE
Approvement

### ISSUE THREAD

**Issue by clemg** [Bo-Duke/Manu-Auto-Correct#16]
There is a little problem with some sentences like "La vidéo d'Emmanuel Macron" etc, with are (with the extension) "d'Manu" and the "de Manu", or "qu'Manu" and not "que Manu". So a RegExp could fix that.So a RegExp could fix that.
![screenshot_37](https://user-images.githubusercontent.com/25712482/41795592-96075d14-7663-11e8-978c-ad9e073d821f.png)

**Comment by clementFoyer** [comment]
Fixed in #8
