### ISSUE TITLE
Extension makes some website unusable

### ISSUE THREAD

**Issue by Bo-Duke** [Bo-Duke/Manu-Auto-Correct#19]
On some websites, for example [CityMapper](https://citymapper.com) the extension seems to create huge problems with the website's layout :
![citymapper](https://user-images.githubusercontent.com/9383709/41800472-09da0b94-7676-11e8-9369-f80318f13906.png)

I noticed this on some JS-heavy websites like this one, anyone has any idea what could cause this?

The problem is also there with https://github.com/Bo-Duke/Spider-Man-Auto-Correct so it isn't a problem with one of the regex.

**Comment by TheIndra55** [comment]
Maybe you shouldn't replace it in the whole source only in the `<body>` element

**Comment by timotheeandres** [comment]
@TheIndra55 Maybe <title> too

**Comment by Bo-Duke** [comment]
Yep! That was totally it, thanks a lot

**Comment by pstch** [comment]
This still happens on some websites (for example: [AirBNB's french homepage](https://www.airbnb.fr/)).

EDIT: My last update was on June 23, I see that this fix was made on June 24. I tried to update again, but there seems not to be any more recent version. Should I install from source, or will the version on addons.mozilla.org be updated again ?

**Comment by Bo-Duke** [comment]
I'm not the one updating the Firefox version unfortunately 😕
