### ISSUE TITLE
« nouveau président » changé en « nouveà Manu »

### ISSUE THREAD

**Issue by Bromind** [Bo-Duke/Manu-Auto-Correct#20]
Sur la version Firefox (donc sans doute aussi sur la version Chrome, mais à confirmer), l'expression rationnelle attrape « nouveau président ». Il faudrait rajouter un blanc en début de l'expression.

![2018-06-23-093442_541x51_scrot](https://user-images.githubusercontent.com/6730712/41807031-cb710b52-76c8-11e8-9533-84b2dd86f549.png)

**Comment by Bo-Duke** [comment]
Je n'ai pas le problème sous Chrome, la version Firefox est un peu en retard parce qu'elle n'est pas maintenue par moi 
![chrome](https://user-images.githubusercontent.com/9383709/41807329-d6d671d0-76cd-11e8-9fd2-ec09a877abc3.png)

Ça devrait être réglé sous peu :)

**Comment by Robou** [comment]
Coucou (je suis celui qui maintient la version firefox)
Ca y est j'ai corrigé. J'avais fait quelques essais pour remplacer "au président" par "à Manu", d'où le problème.
J'ai corrigé en supprimant la fonctionnalité et en revenant à la version ci présente sur github (à un ou deux trucs près).

J'ai fait une page sur regexr pour tester tout ça : [https://regexr.com/3rfo6](https://regexr.com/3rfo6)

**Comment by Bromind** [comment]
Niquel. Btw @Robou, est-ce que tu as un dépôt public de la version firefox que tu maintiens pour éviter de spammer ce dépôt ?

**Comment by Robou** [comment]
non, et je ne penses pas en faire. C'est plus simple de centraliser ici,
pour le peu qu'il y a. Et de toute façon dans quelques jours tout le monde
aura oublié tout ça ! :D
