### ISSUE TITLE
Extension messes up some website's style

### ISSUE THREAD

**Issue by babolivier** [Bo-Duke/Manu-Auto-Correct#24]
With the extension enabled, this website:

https://www.welcometothejungle.co/companies/qwant-research/jobs

Which usually looks like this:

![image](https://user-images.githubusercontent.com/5547783/50597105-2337ec80-0e9e-11e9-9f8e-65dbf42fe0da.png)

Looks like this:

![image](https://user-images.githubusercontent.com/5547783/50597174-5bd7c600-0e9e-11e9-8dfa-c2cf0f399cb8.png)

It basically don't have any style any more (or at least almost none), and this is only happening with the extension enabled. This is one website among many, and I didn't find the time to investigate what the extension is doing to cause this.

**Comment by Bo-Duke** [comment]
Firefox or Chrome?

**Comment by babolivier** [comment]
Gha, sorry, forgot to add that info: Firefox 64.0.

**Comment by Bo-Duke** [comment]
Yeah, I’m not the one publishing the Firefox one, I’ll try to contact the maintener so he can pull the fix.
Can you just try it on a Chromium browser just to be sure?

**Comment by vinz243** [comment]
Same, the issue comes with websites using styled-component I believe

**Comment by Bo-Duke** [comment]
@vinz243 Firefox too?

**Comment by vinz243** [comment]
Yes indeed,  works fine on chrome

**Comment by Robou** [comment]
Hi @babolivier I am the "maintainer" of the Firefox version.
I fixed the bug today by copy-pasting @Bo-Duke code.
It works fine now for me.
I also updated the inverse extension! (all "Manu" occurences replaced by "Monsieur le Président" ^^)
[https://addons.mozilla.org/fr/firefox/user/14109046/](https://addons.mozilla.org/fr/firefox/user/14109046/)

**Comment by babolivier** [comment]
Seems to work fine now, thanks! :)
