### ISSUE TITLE
You should also replace on "Macron"

### ISSUE THREAD

**Issue by TheCapsLock** [Bo-Duke/Manu-Auto-Correct#4]
as seen here there is a case where it is not replaced by "Manu": 
![capture d ecran de 2018-06-21 11-23-19](https://user-images.githubusercontent.com/3322481/41710261-857900b6-7545-11e8-8dda-e4175282859b.png)

**Comment by Gougere89** [comment]
But there would be a problem with "Brigitte Manu" ☺

**Comment by clemg** [comment]
In this case, you should also change "Brigitte Macron" and all the things related with her with "La prof" or something representing her.

**Comment by jacqueslelezard** [comment]
You can fix this by replacing first "Brigitte Manu" by a random id, replace all the other instances of Manu and then replace the previous id by "Brigitte Macron" again :)

**Comment by clementFoyer** [comment]
Bof bof pour ce qui est de remplacer Brigitte par quoi que ce soit. Elle n'a rien demandé, y'a pas de raison de lui taper dessus.

**Comment by lefuturiste** [comment]
mdr, je pense qu'on peut pousser le concept encore plus loin avec les regex et faire un truc propre

**Comment by clemg** [comment]
Le problème de pousser le concept encore plus loin, c'est que ça fait trop durer la blague et que ça devient plus juste plus drôle en fait.. Le but à la base était de faire quelque chose de simple pour que tout ce qui est en rapport avec Macron devienne Manu. C'est comme les trucs avec sa femme, tant que personne ne lui donne un petit surnom ça sert à rien de faire une RegExp pour elle ^^ (même si oui c'est drôle xD)

**Comment by Bo-Duke** [comment]
Je suis assez d'accord avec @Thosquey, je préfère garder le truc plutôt simple, même si ça veut dire que dans quelques cas un "Macron" reste dans un article ou deux.

De plus, j'ai eu plusieurs de mails de gens très heureux de proposer leurs ajouts et modifications de regex alors qu'il n'ont pas de passé informatique, ça donne un tout autre intérêt à l'extension de garder un code simple et compréhensible par tous 😄 

En tout cas merci beaucoup pour l'intérêt que vous apportez à cette petite blague haha !
